logging:
    level:
        org.joolzminer.examples: debug

application:

    outputPath:
        /tmp/github-archive      # src/main/resources/data
        
    files: 
        - http://data.githubarchive.org/2015-03-01-0.json.gz
        - http://data.githubarchive.org/2015-03-01-1.json.gz
        - http://data.githubarchive.org/2015-03-01-2.json.gz
        - http://data.githubarchive.org/2015-03-01-3.json.gz
        - http://data.githubarchive.org/2015-03-01-4.json.gz
        - http://data.githubarchive.org/2015-03-01-5.json.gz
        - http://data.githubarchive.org/2015-03-01-6.json.gz
        - http://data.githubarchive.org/2015-03-01-7.json.gz
        - http://data.githubarchive.org/2015-03-01-8.json.gz
        - http://data.githubarchive.org/2015-03-01-9.json.gz
        - http://data.githubarchive.org/2015-03-01-10.json.gz
        - http://data.githubarchive.org/2015-03-01-11.json.gz
        - http://data.githubarchive.org/2015-03-01-12.json.gz
        - http://data.githubarchive.org/2015-03-01-13.json.gz
        - http://data.githubarchive.org/2015-03-01-14.json.gz
        - http://data.githubarchive.org/2015-03-01-15.json.gz
        - http://data.githubarchive.org/2015-03-01-16.json.gz
        - http://data.githubarchive.org/2015-03-01-17.json.gz
        - http://data.githubarchive.org/2015-03-01-18.json.gz
        - http://data.githubarchive.org/2015-03-01-19.json.gz
        - http://data.githubarchive.org/2015-03-01-20.json.gz
        - http://data.githubarchive.org/2015-03-01-21.json.gz
        - http://data.githubarchive.org/2015-03-01-22.json.gz
        - http://data.githubarchive.org/2015-03-01-23.json.gz
                        